### ISSUE TITLE
请问有demo代码吗？Ionic4安装了之后，检测到一直用的是系统的webview，

### ISSUE THREAD

**Issue by AlwaysLoveme** [zsxsoft/cordova-plugin-x5-tbs#11]
目前用的Ionic4，一开始安装的cordova-plugin-x5-webview，，作者也只讲了安装好就可以了，事实证明肯定还有其他的配置需要做，于是我去TBS官网，但我不是搞原生的，看起来很吃力，需要请教一下，除了安装这个插件，还需要配置哪些地方才可以生效，谢谢

**Comment by zsxsoft** [comment]
我目前有一段时间没研究这个了，暂时帮不到你，抱歉

**Comment by ayaka209** [comment]
我猜MainActivity的代码没改？
另外ionic v4自带一个webview插件也许和这个有关

等我过几天踩到这个坑了有答案告诉你

**Comment by AlwaysLoveme** [comment]
> 我猜MainActivity的代码没改？
> 另外ionic v4自带一个webview插件也许和这个有关
> 
> 等我过几天踩到这个坑了有答案告诉你

试过了，还是无法切换到X5，估计是ionic4不兼容，

**Comment by zsxsoft** [comment]
@AlwaysLoveme 看一下我更新的readme
