### ISSUE TITLE
是不是默认都会使用X5

### ISSUE THREAD

**Issue by kuyoonjo** [zsxsoft/cordova-plugin-x5-tbs#2]
如 cordova-plugin-inappbrowser
会使用X5打开网页吗？

**Comment by zsxsoft** [comment]
inappbrowser没测试过，我怀疑不会，你可以自己试试……

**Comment by kuyoonjo** [comment]
QbSdk.initX5Environment(this, null);

关于这行，到哪里去import QbSdk?
