### ISSUE TITLE
惭愧，想问下怎么用，是不是不能直接继承CordovaActivity了

### ISSUE THREAD

**Issue by silentcmz** [zsxsoft/cordova-plugin-x5-tbs#3]
RT~

**Comment by zsxsoft** [comment]
什么怎么用……

**Comment by silentcmz** [comment]
额，我现在的问题就是 ionic Angular 在Android4.4以下的手机上全是白屏，无法显示H5页面，所以想换内核，但是换了你这个插件，还是白屏~~不知道是不是没设置好

**Comment by zsxsoft** [comment]
https://x5.tencent.com/tbs/guide/sdkInit.html
看第五章

``
显示网页文字时，可通过长按选择文字的标识判断，如下水滴状选择效果是x5webview 的标志：
``

![image](https://user-images.githubusercontent.com/2398785/26877457-a4f5326a-4bbc-11e7-9338-6edebc516ff5.png)

**Comment by zsxsoft** [comment]
然后为什么不能用：https://x5.tencent.com/tbs/technical.html#/detail/sdk/1/4adcd6fa-dbe7-4c82-8304-541cc73b8c1e
