### ISSUE TITLE
请问这个要在哪加?QbSdk.initX5Environment(this, null);

### ISSUE THREAD

**Issue by hhiew** [zsxsoft/cordova-plugin-x5-tbs#4]
我直接修改%cordova%\platforms\android\CordovaLib\src\org\apache\cordova.java,
选 import com.tencent.smtt.sdk.QbSdk;
然后在onCreate中加入QbSdk.initX5Environment(this, null);
cordova build android时报错..报com.tencent.smtt.sdk.QbSdk找不到...
platforms\android\lib目录下有(无替换了)tbs_sdk_thirdapp_v3.2.0.1104_43200_sharewithdownload_withfilereader_withoutGame_obfs_20170609_115346
我看了这个jar有 com.tencent.smtt.sdk.QbSdk这个包..

**Comment by zsxsoft** [comment]
建议你完全删了重来吧……

**Comment by ayaka209** [comment]
应该在platforms\android\src\包名\MainActivity.java这里加吧。
当然import是少不了的
