### ISSUE TITLE
个人觉得这个项目还是有意义的

### ISSUE THREAD

**Issue by hhiew** [zsxsoft/cordova-plugin-x5-tbs#6]
官方的插件不好用.装上后很多cordova插件不能调用

**Comment by zsxsoft** [comment]
两个代码理应差不多吧……可以详细说说怎么个不能掉用法

**Comment by silentcmz** [comment]
的确是，反正我更换完官方之后，好多插件用不了

**Comment by hhiew** [comment]
@zsxsoft 拿我出问题的插件来例子,是一个二维码扫描的,同样的代码没做任何改动,用你的就可以.官方的不行,附上代码
 `<template>
  <span
    v-if="showType=='icon'"
    class="iconfont icon-yduiscan"
    style="font-size: .4rem;color:#ddd"
    v-on:click="openScanner"
  >
  </span>
  <yd-button
    v-else
    :type="buttonType"
    v-on:click.native="openScanner"
  >
    扫描
  </yd-button>
</template>
<script>
  export default {
    name: 'nb-scanner',
    props: {
      buttonType: {
        type: String,
        default: function () {
          return 'primary';
        }
      },
      showType: {
        type: String,
        default: function () {
          return 'icon';
        }
      },
      handle: {
        type: String,//扫描结果的处理器, self:自己处理,event:提交scanDone事件,
        // 传入扫描结果对像:{test:'扫描的文本',format:'条码的格式',cancelled:boonlen值,是否已取消}
        default: function () {
          return 'self';
        }
      },
      cameraOption: {
        type: Object,
        default: function () {
          return {
            preferFrontCamera: false, // iOS and Android 更喜欢前置摄像头
            showFlipCameraButton: true, // iOS and Android 显示翻转按钮
            showTorchButton: true, // iOS and Android 显示闪光灯按钮
            torchOn: false, // Android, launch with the torch switched on (if available) 闪光灯是否开启
            saveHistory: false, // Android, save scan history (default false) 是否存储历史扫描记录
            prompt: '条码扫描', // Android 提示文字
            resultDisplayDuration: 1500, // Android, display scanned text for X ms. 0 suppresses it entirely, default 1500 显示扫描文本的时间ms
            formats: 'all', // default: all but PDF_417 and RSS_EXPANDED  扫描格式
            orientation: 'portrait', // Android only (portrait|landscape), default unset so it rotates with the device 屏幕翻转模式
            disableAnimations: true, // iOS 是否关闭动画
            disableSuccessBeep: false // iOS 是否关闭成功的声音
          };
        }
      }
    },
    data () {
      return {
        barcodeScanner: null,
      };
    },
    methods: {
      instrumentHandle (data) {
        //浏览器测试

        //浏览器测试
        if (data.rent_status == '1' && data.rent_back_id != null) {
          this.$router.push({
            path: '/admin/rentback/edit/' + data.rent_back_id,
            params: {id: data.rent_back_id},
            query: {scandata: data}
          });
        } else if (data.rent_status == '1' && data.rent_back_id == null) {
          this.$router.push({
            path: '/admin/rentback/create',
            query: {scandata: data}
          });
        } else if (data.locked_time != null
          && (data.rent_order_id != 0 && data.rent_order_id != null)
        ) {
          this.$router.push({
            path: '/admin/rentorder/edit/'+data.rent_order_id,
            params: {id: data.rent_order_id},
            query: {scandata: data}
          });
        } else if (data.locked_time != null
          && (data.sales_order_id != 0 && data.sales_order_id != null)
        ) {
          this.$router.push({
            path: '/admin/salesorder/edit/'+data.sales_order_id,
            params: {id: data.sales_order_id},
            query: {scandata: data}
          });
        } else {
          this.$router.push({
            path: '/admin/productserinum/edit/'+data.id,
            params: {id: data.id},
            query: {scandata: data}
          });
        }
      },
      sendContent (content) {
        let backdata = null;
        this.$http.post('admin/barcode', {
          content: content
        }).then((response) => {
          let rtndata = response.data;
          if (rtndata.status === true || rtndata.status === 'true') {
            switch (rtndata.type) {
              case 'instrument':
                this.instrumentHandle(rtndata.data);
                break;
              default:
                alert('服务器响应未知的处理类型');
            }
          } else {
            alert(rtndata.info);
          }
        });
      },
      openScanner () {
        let self = this;
        if (this.barcodeScanner == null) {
          alert('无法启用相机');
          return;
        }
        //如未传入处事函数则由组件来处理
        if (self.handle == 'self') {
          this.barcodeScanner.scan((result) => {
            if (!result.cancelled) {
              let content = result.text;
              self.sendContent(content);
            }
          }, (err) => {
            alert('扫描错误,错误信息:' + err);
            return;
          }, self.cameraOption);
        } else {
          //将处理结果交给传入的handle处理
          this.barcodeScanner.scan(
            (result) => {
              self.$emit('scanDone', result);
            },
            (err) => {
              alert('扫描错误,错误信息:' + err);
              return;
            },
            self.cameraOption
          );

        }

      }
    },
    created () {
      //插件是否存在
      if (window.cordova != null
        && window.cordova.plugins != null
        && window.cordova.plugins.barcodeScanner != null) {
        this.barcodeScanner = window.cordova.plugins.barcodeScanner;
      } else {
        this.barcodeScanner = {
          scan: function (success, error, option) {
            let content = prompt('请手动输入条形编码');
            if (content == '') {
              if (typeof error == 'function') {
                error('未输入内容');
              }
            } else {
              if (typeof success == 'function') {
                success({text: content, format: '', cancelled: content == null});
              }
            }

          }
        };
      }
    }
  };
</script>
<style>
  @import '../assets/iconfont/style.css';
  @font-face {
    font-family: YDUI-ICONS;
    src: url("../assets/iconfont/font_1461139240_0312312.ttf") format("truetype")
  }
</style>
`

**Comment by zsxsoft** [comment]
@hhiew 
我对比了一下两份代码，最大的差别在这个函数（我的是左边的）
我估计是官方没实现全……

![image](https://user-images.githubusercontent.com/2398785/32132824-7ae751ea-bbfd-11e7-8820-16af1f3c9322.png)

**Comment by ayaka209** [comment]
官方issue也没人理，也很久没更新了，这边还有作者维护，真是十分感谢！

**Comment by finscn** [comment]
我也决定放弃官方的 回到这个项目了.

**Comment by K68** [comment]
请收下我的膝盖，被官方的插件折磨了两天，终于找到你这里，作者幸苦了
